### Configurações Globais
@baseUrl = http://localhost:3000
@contentType = application/json

### Verifica o status do servidor
GET {{baseUrl}}/alive
Accept: {{contentType}}

### Obtém a equipe
GET {{baseUrl}}/team
Accept: {{contentType}}


### Obtém todas as tarefas
GET {{baseUrl}}/api/fake_tasks
Accept: {{contentType}}

### Obtém todas as tarefas a partir do título
GET {{baseUrl}}/api/fake_tasks?search=Praticar Listening
Accept: {{contentType}}

### Obtém todas as tarefas completas
GET {{baseUrl}}/api/fake_tasks?completed=false
Accept: {{contentType}}

### Obtém todas as tarefas com prioridade alta
GET {{baseUrl}}/api/fake_tasks?priority=high
Accept: {{contentType}}

### Criar um nova tarefa
POST {{baseUrl}}/api/fake_tasks
Content-Type: {{contentType}}

{
  "title": "Estudar Alemão",
  "priority": "high",
  "isCompleted":false
}

### Obtém uma tarefa pelo id
GET {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
Accept: {{contentType}}

### Atualizar uma tarefa
PUT {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
Content-Type: {{contentType}}

{
  "title": "Estudar Python",
  "priority": "normal",
  "isCompleted": false
}

### Atualizar uma tarefa
PATCH {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
Content-Type: {{contentType}}

{
  "title": "Study Typescript",
  "priority": "low",
  "isCompleted": true
}

### Atualizar uma tarefa
PATCH {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
Content-Type: {{contentType}}

{
  "title": "Study C#.Net"
}

### Atualizar uma tarefa
PATCH {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
Content-Type: {{contentType}}

{
  "priority": "low"
}

### Atualizar uma tarefa
PATCH {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
Content-Type: {{contentType}}

{
  "isCompleted": false
}


### Deletar uma tarefa
DELETE {{baseUrl}}/api/fake_tasks/783d0f72-45c6-4339-863f-aafdcc367087
